# Generated by Django 4.2 on 2023-05-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_multiple_types_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carousel_2_img',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='carousel_3_img',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
