# Generated by Django 4.2 on 2023-05-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_carousel_2_img_product_carousel_3_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='techspec',
            name='product_helper',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
