# Generated by Django 4.2 on 2023-05-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_alter_product_short_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techspec',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='techspec',
            name='product_helper',
        ),
        migrations.AddField(
            model_name='techspec',
            name='product_helper',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
    ]
